; 8086 Assembly generated by NCC Compiler
#width 16
#origin 0x0

; Function: helloWorld
_helloWorld:
    push bp
    mov bp, sp

    ; Local variable declaration: a
    mov ax, 3 ; Load literal
    push ax ; Initialize local variable
    ; Local variable declaration: b
    mov ax, 33 ; Load literal
    push ax ; Initialize local variable
    ; Return statement
    mov ax, [bp-2] ; Load local variable a
    push ax ; Save left operand
    mov ax, [bp-4] ; Load local variable b
    mov bx, ax ; Right operand to bx
    pop ax ; Restore left operand
    add ax, bx ; Addition
    ; Return value in AX
    jmp _helloWorld_exit

_helloWorld_exit:
    ; Standard function epilogue
    mov sp, bp
    pop bp
    ret